package model

import (
	"testing"

	"github.com/QuantumNous/new-api/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestInviteCombinedSummaryAcrossRoles(t *testing.T) {
	inviteLab(t, 24)
	require.NoError(t, AdminInviteFunding(2, 10000, "add", "combined-b-first-credit001"))
	require.NoError(t, AdminInviteFunding(3, 20000, "add", "combined-c-first-credit001"))
	b, err := GetInviteSummary(2)
	require.NoError(t, err)
	assert.EqualValues(t, 2, b.Qualified)
	assert.EqualValues(t, 2, b.Pending)
	assert.EqualValues(t, 2400, b.PendingQuota)
	assert.Zero(t, b.Balance)
	_, err = TransferInviteRewards(2, 0, "combined-pending-transfer")
	require.ErrorIs(t, err, ErrInviteUnavailable)
	require.NoError(t, ReleaseInviteRewards(common.GetTimestamp()+90000))
	b, err = GetInviteSummary(2)
	require.NoError(t, err)
	assert.EqualValues(t, 2, b.Released)
	assert.Zero(t, b.Pending)
	assert.Zero(t, b.PendingQuota)
	assert.Equal(t, 1600, b.Balance)
	assert.Equal(t, 10800, inviteUserState(t, 2).Quota)
	require.NotNil(t, b.Lifetime)
	assert.EqualValues(t, 2400, *b.Lifetime)
	amount, err := TransferInviteRewards(2, 0, "combined-released-transfer")
	require.NoError(t, err)
	assert.Equal(t, 1600, amount)
	_, err = TransferInviteRewards(2, 0, "combined-released-transfer")
	require.NoError(t, err)
	assert.Equal(t, 12400, inviteUserState(t, 2).Quota)
	c, err := GetInviteSummary(3)
	require.NoError(t, err)
	assert.EqualValues(t, 1, c.Qualified)
	assert.EqualValues(t, 1, c.Released)
	assert.Zero(t, c.Balance)
	require.NotNil(t, c.Lifetime)
	assert.EqualValues(t, 1600, *c.Lifetime)
	_, err = TransferInviteRewards(3, 0, "combined-invitee-transfer")
	require.ErrorIs(t, err, ErrInviteUnavailable)
	assert.Equal(t, 21600, inviteUserState(t, 3).Quota)
	require.NoError(t, ReverseInviteRewards("admin:combined-b-first-credit001", 5000))
	b, err = GetInviteSummary(2)
	require.NoError(t, err)
	assert.EqualValues(t, 1, b.Reversed)
	assert.Zero(t, b.Balance)
	assert.Equal(t, 12000, inviteUserState(t, 2).Quota)
	require.NoError(t, ReverseInviteRewards("admin:combined-c-first-credit001", 20000))
	b, err = GetInviteSummary(2)
	require.NoError(t, err)
	assert.EqualValues(t, 2, b.Reversed)
	require.NotNil(t, b.Lifetime)
	assert.EqualValues(t, 2400, *b.Lifetime)
	assert.Equal(t, 10400, inviteUserState(t, 2).Quota)
}

func TestInviteCombinedSummaryPendingRecoveryAndRateSnapshot(t *testing.T) {
	inviteLab(t, 24)
	require.NoError(t, AdminInviteFunding(2, 10000, "add", "combined-refund-b-credit01"))
	require.NoError(t, AdminInviteFunding(3, 20000, "add", "combined-refund-c-credit01"))
	require.NoError(t, ReverseInviteRewards("admin:combined-refund-b-credit01", 5000))
	p, err := GetInviteProgram()
	require.NoError(t, err)
	p.RateBps = 1000
	require.NoError(t, SaveInviteProgram(p))
	b, err := GetInviteSummary(2)
	require.NoError(t, err)
	assert.EqualValues(t, 2000, b.PendingQuota)
	assert.EqualValues(t, 2, b.Pending)
	assert.EqualValues(t, 1, b.Reversed)
	require.NoError(t, ReleaseInviteRewards(common.GetTimestamp()+90000))
	b, err = GetInviteSummary(2)
	require.NoError(t, err)
	assert.Equal(t, 1600, b.Balance)
	assert.Equal(t, 10400, inviteUserState(t, 2).Quota)
	assert.EqualValues(t, 2, b.Released)
	require.NotNil(t, b.Lifetime)
	assert.EqualValues(t, 2000, *b.Lifetime)
}
